data:
    raw_data_path: "data/raw/FloodPrediction.csv"
    processed_data_path: "data/processed/clean_flood_data.csv"
    reference_data_path: "data/reference_data/reference.csv"
    train_data_path: "data/training_data/train.csv"
    test_data_path: "data/testing_data/test.csv"
    features_set: ['Min_Temp', 'Rainfall','Cloud_Coverage', 'Station_Number', 'ALT', 'rain_latitude','rain_longitude', 'dist_to_water', 'Flood'] 
    
modelling:
    random_state: 42
    test_size: 0.2
    target: 'Flood'
    models_directory: "models/"
    eval_metric: "f1"